### ISSUE TITLE
Kotlin `Pair` for `rxAsyncGet`?

### ISSUE THREAD

**Issue by neozax** [Ganet/rxaerospike#1]
It seems like if my java project uses `rxAsyncGet`, it has to know Kotlin's `Pair` class since that's part of its return type. I don't want my java project to know anything about Kotlin, what's a good solution?

**Comment by jacinpoz** [comment]
Java 8 does not have a proper class to represent a Tuple or a Pair (although javafx has one). I could have used any of the third party libraries implementing it (like Apache Commons), but it would add an extra dependency on the project for a very silly addition.

I decided to use Kotlin Pair because Kotlin is already part of the project, and it has good language support.

However, I do understand your position and if it makes it any better, I can create a wrapper class called "AerospikeKeyValue" or "AerospikeResult" and return this instead.

What do you think about this solution?

**Comment by neozax** [comment]
I like the solution, it would make this library easier to work with.

**Comment by jacinpoz** [comment]
I implemented `AerospikeResult<V>` and `AerospikeArrayResult<V>`  data wrappers. They replace Kotlin's `Pair` class and use a generic value for the result. This decision was made because Aerospike get/exists/execute operations always return a `Key `or an array of `Key `objects, but the result itself could be a `Boolean `(exists operation), a `Record `(get operation) or any `Object `(execute operation).

The changes are available in version 0.3.0.
